=== CarrowZhu/jsoup2bean/src/test/resources/htmlExtractor.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
	targetNamespace="http://www.siyuan.com/htmlExtractor" 
	xmlns="http://www.siyuan.com/htmlExtractor" elementFormDefault="qualified">

	<xs:element name="htmlExtractor">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="bean" />
				<xs:element ref="list" />
				<xs:element ref="property" />
			</xs:choice>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="bean">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="bean"></xs:element>
				<xs:element ref="list"></xs:element>
				<xs:element ref="property"></xs:element>
				<xs:element ref="combine"></xs:element>
			</xs:choice>
			<xs:attributeGroup ref="extractor"/>
        </xs:complexType>
	</xs:element>
	  
	<xs:element name="list">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="bean"></xs:element>
				<xs:element ref="list"></xs:element>
				<xs:element ref="property"></xs:element>
				<xs:element ref="combine"></xs:element>
			</xs:choice>
			<xs:attributeGroup ref="extractor"/>
			<xs:attribute name="elementType" type="xs:string"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="property">
		<xs:complexType>
			<xs:attributeGroup ref="extractor">
			     <xs:annotation>
			         <xs:documentation><![CDATA[
			             The supported type is [byte, char, short, int, long, float, double, boolean, 
			             string, date] and [java.lang.Byte, java.lang.Character, java.lang.Short, 
			             java.lang.Integer, java.lang.Long, java.lang.Float, java.lang.Double, 
			             java.lang.Boolean, java.lang.String, java.util.Date]
			         ]]></xs:documentation>
			     </xs:annotation>
			</xs:attributeGroup>
			<xs:attribute name="index">
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:minInclusive value="0"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="value" type="xs:string"/>
			<xs:attribute name="text" type="xs:boolean"/>
			<xs:attribute name="format" type="xs:string"/>
			<xs:attribute name="pattern" type="xs:string"/>
			<xs:attribute name="group">
			     <xs:simpleType>
                    <xs:restriction base="xs:integer">
                        <xs:minInclusive value="0"/>
                    </xs:restriction>
                </xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	
	<xs:attributeGroup name="extractor">
		<xs:attribute name="name" type="xs:string"/>
		<xs:attribute name="type" type="xs:string"/>
		<xs:attribute name="selector" type="xs:string"/>
	</xs:attributeGroup>
	
	<xs:element name="combine">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="bean"></xs:element>
				<xs:element ref="list"></xs:element>
				<xs:element ref="property"></xs:element>
				<xs:element ref="combine"></xs:element>
			</xs:choice>
			<xs:attribute name="selector" type="xs:string"></xs:attribute>
		</xs:complexType>
	</xs:element>
				
</xs:schema>

=== CarrowZhu/jsoup2bean/src/test/resources/house.xml
<?xml version="1.0" encoding="UTF-8"?>
<htmlExtractor xmlns="http://www.siyuan.com/htmlExtractor" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:schemaLocation="http://www.siyuan.com/htmlExtractor htmlExtractor.xsd ">
    
    <bean name="house" type="com.siyuan.entity.House">
        <property name="title" selector="div.pagemain_saledetail div.house_slogan div.house_title h2"/>
    	<combine selector="#detailconMainBase">
    	    <property name="totalPrice" selector="span.color_f60" pattern="(.*)万" group="1"/>
    	    <property name="price" selector="div.another_info span" pattern="单价：(.*)元/㎡" group="1"/>
    	    <property name="roomCount" selector="ul div.clearfix span.fl" index="1" pattern="(.*)房(.*)厅" group="1"/>
    	    <property name="livingCount" selector="ul div.clearfix span.fl" index="1" pattern="(.*)房(.*)厅" group="2"/>
    	    <property name="area" selector="ul div.clearfix span.fl" index="3" pattern="(.*)㎡" group="1"/>
    	    <property name="floor" selector="ul div.clearfix span.fl" index="5" pattern="(.*)层\s/(.*)层" group="2"/>
    	    <property name="decoration" selector="ul div.clearfix span.fl" index="7" />
    	    <property name="direction" selector="ul div.clearfix span.fl" index="9" />
    	    <property name="type" selector="ul div.clearfix span.fl" index="11" />
    	    <property name="bigArea" selector="ul div.clearfix span.fl" index="13" text="false" pattern="(.*)&amp;nbsp;(.*)" group="1"/>
    	    <property name="smallArea" selector="ul div.clearfix span.fl" index="13" text="false" pattern="(.*)&amp;nbsp;(.*)" group="2"/>
    	    <property name="buildTime" selector="ul div.clearfix span.fl" index="15" pattern="(.*)年" group="1" format="yyyy"/>
    	</combine>
    	<bean name="garden" type="com.siyuan.entity.Garden" selector="#detailconMainBase">
    	    <property name="name" selector="ul div.clearfix span.fl" index="17"/>
            <property name="address" selector="ul div.clearfix span.fl" index="19"/>
    	</bean>
    </bean>
    
</htmlExtractor>
